# Generated by Django 2.1.2 on 2018-11-15 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('likes', models.IntegerField(default=0)),
                ('privacy', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('text', models.TextField(help_text='Your post here!', max_length=1000)),
            ],
        ),
    ]
